# Generated by Django 3.2.3 on 2021-05-24 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkrapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diploma',
            options={'verbose_name': 'Диплом', 'verbose_name_plural': 'Дипломы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterField(
            model_name='diploma',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkrapp.student', verbose_name='Автор'),
        ),
    ]
